pipeline:
  test:
    image: node:4.8.3
    environment:
      SELENIUM_START: y
      SELENIUM_HOST: selenium
      SELENIUM_LAUNCH_URL: http://test:3000
      METEOR_ALLOW_SUPERUSER: n
      LC_ALL: "POSIX"
    commands:
      - curl -sL https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh
      - meteor npm install --quiet
      - meteor npm run build --quiet
      - meteor npm run test:browser:ci

services:
  selenium:
    image: selenium/standalone-chrome
