pipeline:
  test:
    image: node:4.8.3
    environment:
      SELENIUM_HOST: selenium
    commands:
      - curl -sL https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh
      - meteor npm install --production --quiet
      - meteor npm install --only=dev --quiet
      - meteor npm test
      - meteor npm run test:server:ci
      - meteor npm run test:browser:ci

services:
  selenium:
    image: selenium/standalone-chrome
