pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  test:
    image: node:4.8.4
    environment:
      LC_ALL: "POSIX"
      METEOR_ALLOW_SUPERUSER: "true"
      SELENIUM_START: "false"
      SELENIUM_HOST: selenium
      SELENIUM_LAUNCH_URL: http://test:3000
      ROOT_URL: http://test:3000
      MONGO_URL: mongodb://mongo/meteor
    commands:
      - curl -sL https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh
      - meteor npm install --quiet
      - meteor npm run build --quiet
      - meteor npm run test:browser:ci
    volumes:
      - /tmp/medialist_test:/tmp/medialist_test

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

services:
  selenium:
    image: selenium/standalone-chrome
    volumes:
      - /tmp/medialist_test:/tmp/medialist_test
  mongo:
    image: mongo:3.4.7
