pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  test:
    image: node:4.8.3
    environment:
      SELENIUM_START: "false"
      SELENIUM_HOST: selenium
      SELENIUM_LAUNCH_URL: http://test:3000
      METEOR_ALLOW_SUPERUSER: "true"
      LC_ALL: "POSIX"
    commands:
      - env
      - curl -sL https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh
      - meteor npm install --quiet
      - meteor npm run test:browser:ci

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

services:
  selenium:
    image: selenium/standalone-chrome
