import '/imports/methods/shared/campaigns'
import '/imports/methods/shared/contacts'
import '/imports/api/contacts/methods'
import '/imports/api/tags/methods'
import '/imports/api/posts/methods'
import '/imports/api/users/methods'
